openapi: 3.0.1
info:
  title: Captcha App
  version: 1.0.0
paths:
  /generate:
    get:
      summary: Generate and store a captcha. It returns the SVG image of the captcha.
      responses:
        "200":
          description: Successful execution
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generateResponse"
        "500":
          description: Fatal error during the request
  /validate:
    post:
      description: Validate a text against a created captcha. It returns true if the provided text is correct and the timeout has not expired, it returns false otherwise.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/validateRequest"
        required: true
      responses:
        "200":
          description: Successful execution
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validateResponse"
        "500":
          description: Fatal error while validating the request
components:
  schemas:
    generateResponse:
      type: object
      properties:
        data:
          type: string
    validateRequest:
      type: object
      properties:
        text:
          type: string
        data:
          type: string
    validateResponse:
      type: object
      properties:
        data:
          type: boolean
