version: "1"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "captcha-app-backend"
    ports:
      - "3001:3001"
  frontend:
    environment:
      - REACT_APP_ENV=production
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "captcha-app-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"
